// Token management utilities for Supabase Edge Functions
// Wrapper around shared token utilities with Deno-specific Supabase client

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
// Import from bundled shared code (generated by npm run bundle:shared)
import { getLinkedInToken as getLinkedInTokenShared } from "./linkedin/tokens.ts";
import type { LinkedInToken } from "./linkedin/types.ts";

/**
 * Get a valid LinkedIn token with automatic refresh
 * Unified function for both personal and community tokens
 * 
 * This is a Deno-specific wrapper that creates a Supabase client
 * and calls the shared token management function.
 */
export async function getLinkedInToken(
  userId: string,
  type: "personal" | "community"
): Promise<LinkedInToken | null> {
  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

  const supabase = createClient(supabaseUrl, supabaseServiceKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });

  // Use shared token management with Deno's env var getter
  return getLinkedInTokenShared(supabase, userId, type, (key: string) =>
    Deno.env.get(key)
  );
}
